const types = {
    GET_ALL_DATA: 'GET_ALL_DATA',
    GET_FILTERED_DATA: 'GET_FILTERED_DATA',
    SELECTED_FILTERS: 'SELECTED_FILTERS',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
    SET_CURRENT_FILTERS: 'SET_CURRENT_FILTERS',
    SEARCH_NAME: 'SEARCH_NAME',
    UPDATE_PAGINATION: 'UPDATE_PAGINATION'
}

export default types;